alias ..='cd ..'
alias ...='cd ..;cd ..'
alias ls='ls --color=auto'
alias ll='ls --color=auto -hl'
alias diff='diff --color'
alias grep='grep --color -ni'
alias nw='source ~/.bin/splitWin.sh'

alias vi='nvim'
alias gst='git status'
alias gc='git checkout'
alias gd='git diff'
alias gb='git branch'
alias gp='git push'
alias gl='git pull'