alias ..='cd ..'
alias ...='cd ..;cd ..'
alias ls='ls --color=auto'
alias ll='ls --color=auto -hl'
alias diff='diff --color'
alias grep='grep --color -ni'

alias gst='git status'
alias gc='git checkout'
alias gd='git diff'
alias gb='git branch -vv'
alias gp='git push'
alias gl='git pull'
alias gw='git show'
alias gam='git commit -am '
alias gr='git remote -v'

